image: atlassian/default-image:4

definitions:
  steps:
    - step: &install
        name: Install
        artifacts: node_modules/**
        script:
          - nvm install
          - npm install
    - step: &build
        name: Build
        script:
          - nvm install
          - npm run build

pipelines:
  branches:
    develop:
      - step: *install
      - step: *build
      - step:
          name: Deploy to staging
          deployment: staging
          script:
            - pipe: atlassian/rsync-deploy:0.12.0
              variables:
                EXTRA_ARGS: --chmod=D2755,F0644
                LOCAL_PATH: ${BITBUCKET_CLONE_DIR}/
                REMOTE_PATH: /var/www/curriculum-vitae/staging/public/
                SERVER: web.jasonroyle.com
                USER: deploy
    master:
      - step: *install
      - step: *build
      - step:
          name: Deploy to production
          deployment: production
          script:
            - pipe: atlassian/rsync-deploy:0.12.0
              variables:
                EXTRA_ARGS: --chmod=D2755,F0644
                LOCAL_PATH: ${BITBUCKET_CLONE_DIR}/
                REMOTE_PATH: /var/www/curriculum-vitae/production/public/
                SERVER: web.jasonroyle.com
                USER: deploy
