image: atlassian/default-image:4

definitions:
  steps:
    - step: &install
        name: Install
        artifacts:
          - node_modules/**
        script:
          - nvm install
          - npm install
    - step: &build
        name: Build
        script:
          - nvm install
          - npm run build
    - step: &nx-install
        name: Install
        artifacts:
          - node_modules/**
        script:
          - nvm install
          - npm ci
    - step: &nx-build
        name: Build
        artifacts:
          - dist/**
        script:
          - nvm install
          - npm run build

pipelines:
  branches:
    develop:
      - step: *nx-install
      - step: *nx-build
      - step:
          name: Deploy to staging
          deployment: Staging
          script:
            - pipe: atlassian/rsync-deploy:0.12.0
              variables:
                EXTRA_ARGS: --chmod=D2755,F0644
                LOCAL_PATH: ${BITBUCKET_CLONE_DIR}/dist/curriculum-vitae/browser/
                REMOTE_PATH: ${REMOTE_PATH}
                SERVER: ${SERVER}
                USER: ${USER}
    master:
      - step: *install
      - step: *build
      - step:
          name: Deploy to production
          deployment: Production
          script:
            - pipe: atlassian/rsync-deploy:0.12.0
              variables:
                EXTRA_ARGS: --chmod=D2755,F0644
                LOCAL_PATH: ${BITBUCKET_CLONE_DIR}/
                REMOTE_PATH: ${REMOTE_PATH}
                SERVER: ${SERVER}
                USER: ${USER}
